//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_kantenbouki : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector3 DrawAnnotation
        {
            get
            {
                return SteamVR_Actions.kantenbouki_DrawAnnotation;
            }
        }
        
        public virtual SteamVR_Action_Boolean SelectMenu
        {
            get
            {
                return SteamVR_Actions.kantenbouki_SelectMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean UndoDrawing
        {
            get
            {
                return SteamVR_Actions.kantenbouki_UndoDrawing;
            }
        }
        
        public virtual SteamVR_Action_Vector2 AdjustDistance
        {
            get
            {
                return SteamVR_Actions.kantenbouki_AdjustDistance;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleMenu
        {
            get
            {
                return SteamVR_Actions.kantenbouki_ToggleMenu;
            }
        }
    }
}
